apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-cluster-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/rrbanda/rhoai-deploy-gitops.git
    targetRevision: helm-deploy-v3.4
    path: helm-deploy/workloads/cluster-config
  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
