apiVersion: v2
appVersion: v3.4.4
description: A Helm chart for installing ODH/RHOAI dependencies and component configurations
keywords:
- openshift
- rhoai
- odh
- ai
- rhaii
- rhai
name: rhai-on-openshift-chart
type: application
version: v3.4.4
