apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
  labels:
    app.kubernetes.io/name: guardrails-orchestrator
    app.kubernetes.io/component: safety
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  disableOrchestrator: true
  enableBuiltInDetectors: true
  enableGuardrailsGateway: false
  replicas: 1
