apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ogx-external-test

labels:
  - pairs:
      app.kubernetes.io/part-of: ogx-external-test

resources:
  - namespace.yaml
  - credentials-secret.yaml
  - ogx-config.yaml
  - ogx-distribution.yaml
