apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-deploy
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rrbanda/rhoai-deploy-gitops.git
    targetRevision: helm-deploy-v3.4
    path: rhoai/deploy/applications
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
