apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-custom-metrics-autoscaler
  namespace: openshift-custom-metrics-autoscaler
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - openshift-custom-metrics-autoscaler
