apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: autorag
spec:
  dspVersion: v2
  apiServer:
    managedPipelines: {}
    pipelineStore: kubernetes
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    minio:
      deploy: true
      image: "quay.io/opendatahub/minio:RELEASE.2023-09-04T19-57-37Z"
  database:
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
