apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: autorag
spec:
  dspVersion: v2
  apiServer:
    managedPipelines: {}
    pipelineStore: kubernetes
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    minio:
      deploy: true
  database:
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
