apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - user-workload-monitoring.yaml
  - milvus.yaml
  - sealed-llm-api-secret.yaml
  - ogx-config.yaml
  - ogxserver.yaml
  - dspa.yaml
