---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llm-api-secret
  namespace: autorag
spec:
  encryptedData:
    llm-api-key: AgCd3NJvFgSNJQ0owoWECQ+z8h7j3tyvGWrE6VeNXtPIJ+LgRV5QMcTnnbyZBGdkSyoD6/nuIXclC4VNLYv5pJjKoOU/7D0biCF2RWKtI9xIlL+LalH0xdrhBcdbxiIwGelhpb2qGY/Nu//SpRO300fHyLFhovaZu735nDKBbOXY/MtWGw9Th8h1dGmyZdjylDYHTvGQBtZdjPoyUQWH0uaRkfIOIOWvNeNjhdwBhcICoMaSuO0iZpmPHut/nF1/NQLMTruZ1fBQvfEnoN3bjsP8ouZHvqKMJZfOAer+EnoFbXsdLvjVdvSipCUjbmj6rDdKTUUxg7MvagF7ZNSGSZTCP3SpWKCpUUY38DrYvNfYz45bpmTFQlAUf4VgFJCe0ro9gsOIW1wBb8SlAqlWuksHFrJLXx70H1EfnFc00K4+bH59mGxwQUnlpxRk//Xl4sEnxowKxFca5P5RP5LQh9SGfdI+ssBCR0ni2d+hs2ePxvcTRMxFF10Fvox8+pA0C8zXzorx1Qpwhdwu0plJaxviA8ch51C4F4xaN78QpYNiybAOXqeiKoGDKtfpGUygMGTkD6zpM5mwW4rT+ooKTyEBlme0T3kSmHnVJlpTf/cvUD3YR24lwRxGGKGcME5kw9uqpIgfFwyNxPa2BO5jlUhJ8EqvMUlfWPLqBBD9L3HnfYlH36wBnrG2D0UEVjxwYTUf3gem0ydG/E/eVKOlzTmEscdaAYLZKFFYzOru2qWprVH5UUm4qY5Hy4GRX1Cdmy31zKcgvQ==
  template:
    metadata:
      name: llm-api-secret
      namespace: autorag
    type: Opaque
