---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llm-api-secret
  namespace: autorag
spec:
  encryptedData:
    llm-api-key: AgAawZFm0r0QxuHOG56TJjPuoRDM5gzQm7aIdzoK7Tnrrf8GSTK7MDHNyZTVGgJV46JrFFAy73GpRWG/wrrBpZY5ubH/NX6PkGF0elfL+/iSrdGZN2pn6+iHxoTryx28UoaXjeruYlEJFFYlOL5cZduxxxl00Qg5uW3XVEmPW6BNZ9qQC3Y8JeQNu8oOSQB7cHdUIPoQmqPw+X/ENK+puijoS6+TOD93EJEdHWq4QMsi3CJDi1XGAl7swnNHSl1g547NTS2Mi/xUbsgirduOZmFtuwl9m2VhN7RTy5qoeGDWpM+oT3NOJ3tD2DmGhCYFidU26YbLkpqlNq6Pwh6HX3JmeZfkT0g4HcVhyKGBsmjl3+TFaejtTu7f6+gqOXF262k0kpTYh2TAfzDN8MqrlU3n7XSq7GDFPbEhRc4HL8PQSD4R8vfIh9a52TDT4miHRw9f6pBUmKpSmtuuyeBuGW/cLcnRZEbhB9cG5ol0yqm7DJg0kAHO++xqUXnSLDS5Cb45fnc9Cdfgw0kVo1FG3FCe7uNky+Riff3eEiyEwRI7kpFFTClsCKMssP61tHXH00TfiLWYGlPx9c4WKgBsWmtJP0MFPW1KxiOiyjj6C4nHGxmSl9KxyiyObhIJCWiw5tYO261SGEF82+kk0I7LJz6tnKt3GOs5+nsETcKgmr48Ihcvc0P6fquk3gK9Khwe3aRbcYHyqKIarYZ7tBgxNlRHCCdsRvP9yeKbMlA7a76V+BL2rBjOHy/XikIr0yIJZn3uDHbAFg==
  template:
    metadata:
      name: llm-api-secret
      namespace: autorag
    type: Opaque
