---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llm-api-secret
  namespace: autorag
spec:
  encryptedData:
    llm-api-key: AgCFeXmssE/7ijjCT8lTZ9DA9JT5/JT6gYyUNZValLP1L33+SSV1B3Easgoh3un0wRPwGmVfE9n97c5gIptUTieSYOfY1BNQ9adri8/pQW8UkxKVCS/3eHZuGCF6Ld4sRqTX38fQLcsHEPqmKmBR0i4FE8yJj+Ut0c4GtedY6MlBkjJTHnnDLh9ftVD2rq11tl6nBSO/zlwUuBlIIoyO2rEvz5jyNjkU+wjhTirUSVMx5vVT7ajFAi3/TcdiLPPGFn+Eo1kDqUlYDI8JhAC7o+NVbYQfw4fhfNqNMnfWhjdtxZVrNcj95EYoYA8qblVKVlRzz8lJa0lmSH390HeuYK2BgRd3JcMqRzriMCYfL6Y1e3unjqYJ6Ik3XzZMDXM8Oj64dRCT9Nge+mb+Tv9u3LZUeHwhg9YinqaLMvI1FQyOBSPcQktDfdz9YGHy9G4IRQ222LzMn8Jnk6o8RJi8gv76wXg/ToweX3sG3C1g2hqL9hY77tczHWe2BWYiqx9KET4oUMtvgpt2zcU8XvOcpHeAqXInF6Az/j8642zlyV9RP7I/KsIVTlZI1bhofY37vNQ8TUnqCOGX+Ce+VHfugsuuriurVvpDPe5H4vvVDUqb4BCBZLQ6ykljfbcfejG0PYGENwSd3vCDVpssdCZvgG9omXh5zUcJ5nYlq389K7NdV9Y63rKZgURxRyZBTzCYWmA0E38KUSMDBBs+Gba2fDYPU3fQrToQZHAy9TPXEiU4MRgCjtd8P8V1h/M71UQ56MlV2YYSjg==
  template:
    metadata:
      name: llm-api-secret
      namespace: autorag
    type: Opaque
