apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: all-minilm-l6-v2
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      runtime: tei-cpu-runtime
    resources:
      requests:
        cpu: "1"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: "1Gi"
