apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: models-embedding

labels:
  - pairs:
      app.kubernetes.io/part-of: embedding-cpu

resources:
  - namespace.yaml
  - serving-runtime.yaml
  - inference-service.yaml
