apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: tei-cpu-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  supportedModelFormats:
    - name: huggingface
      autoSelect: true
  multiModel: false
  containers:
    - name: kserve-container
      image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
      args:
        - "--model-id"
        - "sentence-transformers/all-MiniLM-L6-v2"
        - "--port"
        - "8080"
      env:
        - name: HF_HOME
          value: /tmp/hf-cache
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - name: hf-cache
          mountPath: /tmp/hf-cache
        - name: hf-data
          mountPath: /data
      resources:
        requests:
          cpu: "1"
          memory: "512Mi"
        limits:
          cpu: "2"
          memory: "2Gi"
  volumes:
    - name: hf-cache
      emptyDir: {}
    - name: hf-data
      emptyDir: {}
