apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-inference
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rrbanda/rhoai-deploy-gitops.git
    targetRevision: helm-deploy-v3.5
    path: rhoai/chart
    helm:
      releaseName: rhoai
      skipSchemaValidation: true
      valuesObject:
        skipCrdCheck: true
        profile: rhaii
        components:
          kserve:
            gateway:
              create: true
              name: openshift-ai-inference
              namespace: openshift-ingress
              labels:
                istio.io/rev: openshift-gateway
              spec:
                gatewayClassName: openshift-ai-inference
                listeners:
                - name: https
                  port: 443
                  protocol: HTTPS
                  allowedRoutes:
                    namespaces:
                      from: All
        olm:
          source: REPLACE_WITH_MIRRORED_CATALOG_NAME
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - ServerSideApply=true
