apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: models-as-a-service

labels:
  - pairs:
      app.kubernetes.io/part-of: gemma2-9b-fp8

resources:
  - namespace.yaml
  - chat-template-configmap.yaml
  - llama-stack-config.yaml
  - playground-rbac.yaml
  - llm-inference-service.yaml
  - maas-model-ref.yaml
  - maas-subscription.yaml
  - llamastack-distribution.yaml
