apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: gemma2-9b-fp8
  labels:
    app.kubernetes.io/name: gemma2-9b-fp8
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  modelRef:
    kind: LLMInferenceService
    name: gemma2-9b-fp8
