apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/redhat-cop/gitops-catalog/openshift-ai/operator/overlays/fast?ref=7727f2425149abf9e061665c6d1268a70238c138

patches:
  - target:
      kind: Subscription
      name: rhods-operator
    path: patch-channel.yaml
