apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gemma4-e4b

labels:
  - pairs:
      app.kubernetes.io/part-of: gemma4-e4b

resources:
  - namespace.yaml
  - pvc.yaml
  - download-job.yaml
  - serving-runtime.yaml
  - inference-service.yaml
  - service.yaml
  - route.yaml
