apiVersion: v1
kind: Namespace
metadata:
  name: gemma4-e4b
  labels:
    kubernetes.io/metadata.name: gemma4-e4b
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/name: gemma4-e4b
    app.kubernetes.io/part-of: gemma4-e4b
