apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spoke-workloads-rag
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: rag-spokes
        requeueAfterSeconds: 180
  template:
    metadata:
      name: '{{name}}-autorag-workload'
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        argocd.argoproj.io/skip-reconcile: "true"
        argocd.argoproj.io/sync-wave: "2"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/rrbanda/rhoai-deploy-gitops.git
        targetRevision: helm-deploy-v3.5
        path: rhoai/deploy/03-workloads/autorag
      destination:
        server: https://kubernetes.default.svc
        namespace: autorag
      syncPolicy:
        retry:
          limit: 10
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
