apiVersion: v1
kind: Namespace
metadata:
  name: ai-guardrails
  labels:
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/part-of: guardrails-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "0"
