apiVersion: mcp.x-k8s.io/v1alpha1
kind: MCPServer
metadata:
  name: openshift-mcp-server
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  source:
    type: ContainerImage
    containerImage:
      ref: registry.redhat.io/openshift-mcp-tech-preview/openshift-mcp-server-rhel9:0.3
  config:
    port: 8080
    arguments:
      - --config
      - /etc/mcp-config/config.toml
    storage:
      - path: /etc/mcp-config
        source:
          type: ConfigMap
          configMap:
            name: openshift-mcp-server-config
  runtime:
    security:
      serviceAccountName: mcp-viewer
