apiVersion: v1
kind: ConfigMap
metadata:
  name: openshift-mcp-server-config
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  config.toml: |
    log_level = 5
    port = "8080"
    read_only = true
    toolsets = ["core", "config"]
