apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/part-of: maas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  DB_CONNECTION_URL: "REPLACE_ME"
