apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgresql
  namespace: maas-db
  labels:
    app: postgresql
    app.kubernetes.io/part-of: maas
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgresql
