apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: maas-db
  labels:
    app.kubernetes.io/part-of: maas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  POSTGRES_USER: maas
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_DB: maas
  DATABASE_URL: "postgresql://maas:CHANGE_ME@postgresql.maas-db.svc:5432/maas?sslmode=disable"
