apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-weights
  namespace: orchestrator-rhoai
  labels:
    app.kubernetes.io/name: model-weights
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: orchestrator-rhoai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi
