apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  namespace: orchestrator-rhoai
  labels:
    app.kubernetes.io/name: shared-data
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: orchestrator-rhoai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi
