apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  components:
    aigateway:
      batchGateway:
        managementState: Managed
      managementState: Managed
    aipipelines:
      argoWorkflowsControllers:
        managementState: Managed
      managementState: Managed
    dashboard:
      managementState: Managed
    feastoperator:
      managementState: Managed
    kserve:
      managementState: Managed
      modelCache:
        managementState: Managed
        cacheSize: "50Gi"
        nodeSelector:
          matchLabels:
            nvidia.com/gpu.present: "true"
      modelsAsService:
        managementState: Managed
      nim:
        airGapped: false
        managementState: Managed
      rawDeploymentServiceConfig: Headless
      wva:
        managementState: Managed
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Unmanaged
    llamastackoperator:
      managementState: Removed
    mlflowoperator:
      managementState: Managed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    ogx:
      managementState: Managed
    ray:
      managementState: Managed
    sparkoperator:
      managementState: Managed
    trainer:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    trustyai:
      eval:
        lmeval:
          permitCodeExecution: allow
          permitOnline: allow
      managementState: Managed
      mcpGuardrailsMode: true
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
