apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gpt-oss

labels:
  - pairs:
      app.kubernetes.io/part-of: gpt-oss

resources:
  - serving-runtime.yaml
  - inference-service.yaml
