apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-oss-model-weights
  labels:
    app.kubernetes.io/name: gpt-oss-model-weights
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
