apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  components:
    dashboard:
      managementState: Managed
    workbenches:
      managementState: Removed
    kserve:
      managementState: Managed
    ray:
      managementState: Removed
    trainingoperator:
      managementState: Removed
    kueue:
      managementState: Unmanaged
    modelregistry:
      managementState: Removed
    trustyai:
      managementState: Removed
    datasciencepipelines:
      managementState: Removed
    modelmeshserving:
      managementState: Managed
    codeflare:
      managementState: Removed
    feastoperator:
      managementState: Removed
    llamastackoperator:
      managementState: Removed
