apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  components:
    aigateway:
      managementState: Removed
    aipipelines:
      argoWorkflowsControllers:
        managementState: Removed
      managementState: Managed
    dashboard:
      managementState: Managed
    feastoperator:
      managementState: Removed
    kserve:
      managementState: Removed
      modelsAsService:
        managementState: Removed
      nim:
        airGapped: false
        managementState: Removed
      rawDeploymentServiceConfig: Headless
      wva:
        managementState: Removed
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Unmanaged
    mlflowoperator:
      managementState: Managed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    ogx:
      managementState: Removed
    ray:
      managementState: Managed
    sparkoperator:
      managementState: Managed
    trainer:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    trustyai:
      eval:
        lmeval:
          permitCodeExecution: allow
          permitOnline: allow
      managementState: Managed
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
