apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autorag-workload
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: rhoai-workloads
  source:
    repoURL: https://github.com/rrbanda/rhoai-deploy-gitops.git
    targetRevision: helm-deploy-v3.5
    path: rhoai/base/03-workloads/autorag
  destination:
    server: https://kubernetes.default.svc
    namespace: autorag
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
