apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: openshift-gitops
spec:
  description: RHOAI platform operators and instances
  sourceRepos:
    - https://github.com/rrbanda/rhoai-deploy-gitops.git
    - https://github.com/redhat-cop/gitops-catalog.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
