apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: qwen25-7b-pool
  labels:
    app.kubernetes.io/part-of: llm-d-epp
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetPorts:
    - number: 8000
  selector:
    matchLabels:
      app.kubernetes.io/part-of: llminferenceservice
  endpointPickerRef:
    name: llm-d-epp
    port:
      number: 9002
