apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instance-rhoai
  namespace: openshift-gitops
spec:
  project: platform
  source:
    repoURL: https://github.com/rrbanda/rhoai-deploy-gitops.git
    targetRevision: main
    path: components/instances/rhoai-instance/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: datasciencecluster.opendatahub.io
      kind: DataScienceCluster
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 60s
        maxDuration: 10m0s
        factor: 2
