apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: gpu-l4
spec:
  nodeLabels:
    nvidia.com/gpu.product: NVIDIA-L4
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: gpu-l40s
spec:
  nodeLabels:
    nvidia.com/gpu.product: NVIDIA-L40S
