apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: servicemeshoperator3
    patch: |
      - op: replace
        path: /spec/source
        value: REPLACE_WITH_MIRRORED_CATALOG_NAME
