apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-instances
  namespace: openshift-gitops
spec:
  goTemplate: true
  syncPolicy:
    applicationsSync: sync
  generators:
    - git:
        repoURL: https://github.com/rrbanda/rhoai-deploy-gitops.git
        revision: main
        directories:
          - path: components/instances/*
          - path: components/instances/rhoai-instance
            exclude: true
          - path: components/instances/gpu-workers
            exclude: true
  template:
    metadata:
      name: 'instance-{{ .path.basename }}'
      namespace: openshift-gitops
    spec:
      project: platform
      source:
        repoURL: https://github.com/rrbanda/rhoai-deploy-gitops.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
      ignoreDifferences:
        - group: nvidia.com
          kind: ClusterPolicy
          jsonPointers:
            - /status
        - group: nfd.openshift.io
          kind: NodeFeatureDiscovery
          jsonPointers:
            - /status
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 10
          backoff:
            duration: 60s
            maxDuration: 10m0s
            factor: 2
