apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../projects/base
  - cluster-operators-appset.yaml
  - cluster-instances-appset.yaml
  - cluster-models-appset.yaml
  - cluster-services-appset.yaml
