apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maas-demo-gateway
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/rrbanda/maas-demo.git
    targetRevision: main
    path: clusters/live/gateway
  destination:
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: dscinitialization.opendatahub.io
      kind: DSCInitialization
      jsonPointers:
        - /status
    - group: monitoring.rhobs
      kind: MonitoringStack
      jsonPointers:
        - /status
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
        - /stringData
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 60s
        maxDuration: 10m0s
        factor: 2
