apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-dsc
  namespace: openshift-gitops
spec:
  project: platform
  source:
    repoURL: https://github.com/rrbanda/rhoai-deploy-gitops.git
    targetRevision: rhoai-3.5
    path: components/instances/rhoai-instance/overlays/full
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 30s
        maxDuration: 5m0s
        factor: 2
