apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: qwen25-7b-instruct

resources:
  - namespace.yaml
  - pvc.yaml
  - download-job.yaml
  - llm-inference-service.yaml
  - maas-model-ref.yaml
  - maas-auth-policy.yaml
  - maas-subscription.yaml
  - team-subscriptions.yaml
