apiVersion: v1
kind: Namespace
metadata:
  name: llm-inference
  labels:
    kubernetes.io/metadata.name: llm-inference
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
