apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: remote-inference-tls
  namespace: ai-gateway
  labels:
    app.kubernetes.io/part-of: ai-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  host: qwen25-7b-inference-llm-inference.apps.cluster-4l6x6.4l6x6.sandbox1213.opentlc.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
