apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-gateway

labels:
  - pairs:
      app.kubernetes.io/part-of: ai-gateway

resources:
  - namespace.yaml
  - service-entry.yaml
  - destination-rule.yaml
  - gateway.yaml
  - httproute.yaml
  - auth-policy.yaml
  - envoyfilter-authn-ssl.yaml
