apiVersion: v1
kind: Namespace
metadata:
  name: gpt-oss-120b
  labels:
    kubernetes.io/metadata.name: gpt-oss-120b
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/name: gpt-oss-120b
    app.kubernetes.io/part-of: gpt-oss-120b
