apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  name: nemo-guardrails
  namespace: redhat-ods-applications
spec:
  replicas: 1
  nemoConfigs:
    - name: nemo-guardrails-config
