apiVersion: autoscaling.openshift.io/v1
kind: ClusterAutoscaler
metadata:
  name: default
  labels:
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  podPriorityThreshold: -10
  resourceLimits:
    maxNodesTotal: 20
  scaleDown:
    enabled: true
    delayAfterAdd: 10m
    delayAfterDelete: 5m
    delayAfterFailure: 3m
    unneededTime: 10m
  balanceSimilarNodeGroups: true
  skipNodesWithLocalStorage: true
  maxPodGracePeriod: 600
  maxNodeProvisionTime: 15m
