apiVersion: v1
kind: Namespace
metadata:
  name: models-as-a-service
  labels:
    kubernetes.io/metadata.name: models-as-a-service
    opendatahub.io/dashboard: "true"
    opendatahub.io/generated-namespace: "true"
    app.kubernetes.io/managed-by: maas-controller
