apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator3
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  name: servicemeshoperator3
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  config:
    annotations:
      openshift.io/required-scc: restricted-v2
      target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
