apiVersion: autoscaling.openshift.io/v1
kind: ClusterAutoscaler
metadata:
  name: default
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  podPriorityThreshold: -10
  resourceLimits:
    maxNodesTotal: 20
    gpus:
      - type: nvidia.com/gpu
        min: 0
        max: 8
  scaleDown:
    enabled: true
    delayAfterAdd: 10m
    delayAfterDelete: 5m
    delayAfterFailure: 3m
    unneededTime: 10m
  balanceSimilarNodeGroups: true
  skipNodesWithLocalStorage: true
  maxPodGracePeriod: 600
  maxNodeProvisionTime: 15m
