apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  clusterWide: true
  supersedingHostSubsets: true
  listener:
    tls:
      enabled: true
      certSecretRef:
        name: authorino-tls
